require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GeocodedLocationsController, type: :controller do

  let(:geocoded_locations) { Fabricate.times(7, :geocoded_location, address: Faker::Address.street_address) }
  let(:valid_address_params) { Fabricate.to_params(:geocoded_location, address: "117A Bartlett St., San Francisco") }
  let(:invalid_address_params) { Fabricate.to_params(:geocoded_location, address: "808080808080808080808080") }

  describe 'new' do
    it 'returns status 200' do
      get :new
      expect(response.status).to eq(200)
    end
  end
  describe 'create' do
    context 'when user supplies accurate address and there is a response from the API' do
      it 'creates new instance of geocoded_location' do
        expect{post :create, geocoded_location: valid_address_params}.to change(GeocodedLocation, :count).by(1)
      end
      it 'redirects to root/new_geocoded_location url' do
        post :create, geocoded_location: valid_address_params
        expect(response).to redirect_to(:root)
      end
    end
    context 'when user supplies an address, but address is invalid and an error is returned from the API' do
      it 're-renders the new form' do
        post :create, geocoded_location: invalid_address_params
        expect(response.status).to eq(200)
        expect(response).to render_template("new")
      end
    end
  end
  describe 'destroy' do
    it 'destroys instance of geocoded_location' do
      geocoded_locations
      expect{delete :destroy, id: geocoded_locations.first.id}.to change(GeocodedLocation, :count).by(-1)
    end
  end
end
